export const orderRows=[
    {   ID:1,
        orderNumber:5723223,
        orderItem:'Free Subscription',
        orderDate:'2014-04-03',
        orderCompany:' Company Name',
        orderAmount:'AED o.o7o',
        orderStatus:'completed',
        orderInvoice:<a href={`/invoice`}>view invoice</a>,
     
    },
    {   ID:2,
        orderNumber:8723223,
        orderItem:'Free Subscription',
        orderDate:'2021-04-04',
        orderCompany:' Company Name',
        orderAmount:'AED o.oo3',
        orderStatus:'completed',
        orderInvoice:<a href={`/invoice`}>view invoice</a>,
       
    },
    {   ID:3,
        orderNumber:7723223,
        orderItem:'Free Subscription',
        orderDate:'2016-04-13',
        orderCompany:' Company Name',
        orderAmount:'AED 10.oo',
        orderStatus:'completed',
        orderInvoice:<a href={`/invoice`}>view invoice</a>,
       
    },
    {   ID:4,
        orderNumber:87231423,
        orderItem:'Free Subscription',
        orderDate:'2016-04-03',
        orderCompany:' Company Name',
        orderAmount:'AED o.o8o',
        orderStatus:'completed',
        orderInvoice:<a href={`/invoice`}>view invoice</a>,
       
    },
    {   ID:5,
        orderNumber:872326623,
        orderItem:'Free Subscription',
        orderDate:'2015-04-03',
        orderCompany:' Company Name',
        orderAmount:'AED o9.oo',
        orderStatus:'completed',
        orderInvoice:<a href={`/invoice`}>view invoice</a>,
        
    },

];
export const orderHeadCells=[
    {
      id: 'orderNumber',
      label: 'Order Number',
      doSorting:true,
    },
   
    {
      id: 'orderDate',
      label: 'Order date',
      doSorting:true,
    },
    {
      id: 'orderCompany',
      label: 'Order Company',
      doSorting:false,
    },
    {
      id: 'orderAmount',
      label: 'Order Amount',
      doSorting:false,
    },
    {
      id: 'orderStatus',
      label: 'Order Status',
      doSorting:false,
    },
    {
      id: 'orderInvoice',
      label: 'Order Invoice',
      doSorting:false,
    },
   
];
export const subRows=[
    {   ID:1,
        subName:'SimpleAccounts Chatbot Add-On',
        companyname:'lpha Trading Limited',
        startDate:' 01-05-2021',
        endDate:'31-12-2021',
        renewDate:'25-12-2021',
        subStatus:'Active',
        action:<a href={`/cancel`}>Cancel</a>,    
    },
    {   ID:2,
        subName:'SimpleAccounts Chatbot Add-On',
        companyname:'lpha Trading Limited',
        startDate:' 01-05-2021',
        endDate:'31-12-2021',
        renewDate:'25-12-2021',
        subStatus:'Active',
        action:<a href={`/cancel`}>Cancel</a>,    
    },
    {   ID:3,
        subName:'SimpleAccounts Chatbot Add-On',
        companyname:'lpha Trading Limited',
        startDate:' 01-10-2021',
        endDate:'31-12-2021',
        renewDate:'25-12-2021',
        subStatus:'Active',
        action:<a href={`/cancel`}>Cancel</a>,    
    },
    {   ID:4,
        subName:'SimpleAccounts Chatbot Add-On',
        companyname:'lpha Trading Limited',
        startDate:' 01-05-2021',
        endDate:'20-07-2022',
        renewDate:'25-12-2021',
        subStatus:'Active',
        action:<a href={`/cancel`}>Cancel</a>,    
    },
    {   ID:5,
        subName:'SimpleAccounts Chatbot Add-On',
        companyname:'lpha Trading Limited',
        startDate:' 01-05-2021',
        endDate:'31-12-2021',
        renewDate:'20-07-2022',
        subStatus:'Active',
        action:<a href={`/cancel`}>Cancel</a>,    
    },

];
export const subHeadCells=[
    {
      id: 'subName',
      label: 'subName',
      doSorting:false,
    },
    {
      id: 'companyname',
      label: 'companyname',
      doSorting:false,
    },
    {
      id: 'startDate',
      label: 'startDate',
      doSorting:true,
    },
    {
      id: 'endDate',
      label: 'endDate',
      doSorting:true,
    },
    {
      id: 'renewDate',
      label: 'renewDate',
      doSorting:false,
    },
    {
      id: 'subStatus',
      label: 'subStatus',
      doSorting:false,
    },
  
   
];
export const companyRows=[
    {   ID:1,
        companyId:'c9723',
        companyName:'lpha Trading Limited',
        subsctiption:'impleAccounts Business',
        domain:'alph',
        adminemail:'jphn@gmal.com',
        setupDate:'01-01-2021',
        companyStatus:'ctive',
        companyurl:'https://delta29.app.simpleaccounts.io',
        action:<a href={`/manageCompany`}>Manage</a>,
    },
    {   ID:2,
        companyId:'c9723',
        companyName:'lpha Trading Limited',
        subsctiption:'impleAccounts Business',
        domain:'alph',
        adminemail:'jphn@gmal.com',
        setupDate:' 01-01-2021',
        companyStatus:'ctive',
        companyurl:'https://delta29.app.simpleaccounts.io',
        action:<a href={`/manageCompany`}>Manage</a>,
    },
    {   ID:3,
        companyId:'c9723',
        companyName:'lpha Trading Limited',
        subsctiption:'impleAccounts Business',
        domain:'alph',
        adminemail:'jphn@gmal.com',
        setupDate:' 01-01-2021',
        companyStatus:'ctive',
        companyurl:'https://delta29.app.simpleaccounts.io',
        action:<a href={`/manageCompany`}>Manage</a>,
    },
    {   ID:4,
        companyId:'c9723',
        companyName:'lpha Trading Limited',
        subsctiption:'impleAccounts Business',
        domain:'alph',
        adminemail:'jphn@gmal.com',
        setupDate:' 01-01-2021',
        companyStatus:'ctive',
        companyurl:'https://delta29.app.simpleaccounts.io',
        action:<a href={`/manageCompany`}>Manage</a>,
    },
    {   ID:5,
        companyId:'c9723',
        companyName:'lpha Trading Limited',
        subsctiption:'impleAccounts Business',
        domain:'alph',
        adminemail:'jphn@gmal.com',
        setupDate:' 01-01-2021',
        companyStatus:'ctive',
        companyurl:'https://delta29.app.simpleaccounts.io',
        action:<a href={`/manageCompany`}>Manage</a>,
    },

];
export const companyHeadCells=[
    {
      id: 'companyId',
      label: 'Company id',
      doSorting:false,
    },
    {
      id: 'companyName',
      label: 'Company Name',
      doSorting:false,
    },
  
    {
      id: 'domain',
      label: 'domain',
      doSorting:false,
    },
    {
      id: 'adminemail',
      label: 'admin email',
      doSorting:false,
    },
    {
      id: 'setupDate',
      label: 'setup Date:',
      doSorting:false,
    },
    {
      id: 'companyStatus',
      label: 'company Status',
      doSorting:false,
    },
    {
      id: 'companyurl',
      label: 'company url',
      doSorting:false,
    },
    {
      id: 'action',
      label: 'action',
      doSorting:false,
    },
];